### PR TITLE
News version Optimizer & Pack FR33THY

### PR DESCRIPTION
**Pull request by RutOf**
I added FPS Booster pack to the owners of famous Youtuber / NO Virus

### CODE REVIEW

**Comment by RutOf** [comment]
https://www.youtube.com/@FR33THY

**Comment by RutOf** [comment]
You can check it. because it has no virus since I already tested it myself Hope you add it, but maybe long, so I help you :/ Hope you like it.

**Comment by RutOf** [comment]
Overall, add some FPS tweaks and more.

**Comment by Serups** [comment]
Oh thank you very much but I may have to write to give him more credit.

**Pull request merged**
